name: Test on different environments.

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test_all:
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - run: python3 setup.py pytest

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04, ubuntu-20.04, macos-latest, windows-latest]
